version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel-app
    volumes:
      - ./:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9001:9000" # Custom PHP-FPM port
    networks:
      - laravel-network
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "8081:80" # Custom NGINX port
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: laravel-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: sklinik
    ports:
      - "5432:5432" # Custom PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel-network

  redis:
    image: redis:7
    container_name: laravel-redis
    ports:
      - "6379:6379" # Custom Redis port
    networks:
      - laravel-network

networks:
  laravel-network:

volumes:
  postgres_data:
