version: "3.9"

services:
    laravel_app:
        build:
            context: .
            dockerfile: docker/Dockerfile.app
            args:
                UID: 1000
                GID: 1000
        container_name: laravel_app
        user: "1000:1000"
        volumes:
            - ./:/var/www/laravel_app
        depends_on:
            - laravel_redis
        networks:
            - laravel_network

    laravel_nginx:
        build:
            context: .
            dockerfile: docker/Dockerfile.nginx
        container_name: laravel_nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/laravel_app:ro
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - laravel_app
        networks:
            - laravel_network

    laravel_redis:
        image: redis:alpine
        container_name: laravel_redis
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - ./docker/redis.conf:/usr/local/etc/redis/redis.conf:ro
        networks:
            - laravel_network

    laravel_postgres:
        image: postgres:17
        container_name: laravel_postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234
        volumes:
            - ./docker/postgres_data:/var/lib/postgresql/data
        networks:
            - laravel_network

    laravel_node:
        build:
            context: .
            dockerfile: docker/Dockerfile.node
        container_name: laravel_node
        ports:
            - "5173:5173"
        working_dir: /var/www/laravel_app
        volumes:
            - ./:/var/www/laravel_app
            - /var/www/laravel_app/node_modules
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
    postgres_data: