name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync to cPanel via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: your-cpanel-server.com
          username: your-cpanel-username
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./"
          target: "/home/jura8282/public_html/sklinik.jurnalpendidikan.online"
